name: Nodejs CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Install Wrangler
        uses: cloudflare/wrangler-action@v3
        with: ${{secrets.CLOUDFLARE_API_TOKEN}}

      - name: Login to cloudflare wrangler
        run: wrangler login
          wrangler publish
