name: Nodejs CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - run: npm install
      - run: npm run build --if-present

      - name: Install Wrangler
        run: |
          npm install wrangler

      - name: Login and publish to cloudflare using wrangler wrangler
        run: wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
